name: range-set-list
version: 0.0.7
synopsis: Memory efficient sets with continuous ranges of elements.
description: Memory efficient sets with continuous ranges of elements. List based implementation. Interface mimics 'Data.Set' interface where possible.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: MIT
github: phadej/range-set-list
category: Documentation
extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options: -Wall -fwarn-tabs

dependencies:
  - base >=4.5 && <4.9

library:
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: tests
    dependencies:
      - containers        >=0.5 && <0.6
      - tasty             >=0.8 && <0.12
      - tasty-quickcheck  >=0.8 && <0.9
      - range-set-list
